---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install common system essentials
  apt:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
      - git
      - vim
      - htop

#!Should be removed!
# - name: Add python link pointing to python3
#   file:
#     src: "/usr/bin/python3"
#     dest: "/usr/bin/python"
#     state: link
#   become: true
  
- name: Turn off wifi power saving
  lineinfile:
    path: /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
    regexp: '^wifi.powersave ='
    line: wifi.powersave = 2
  become: true

- name: Disable firewall to allow ROS communication
  command: ufw disable
  become: true