---
- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Upgrade apt packages
  become: true
  apt:
      upgrade: safe

- name: Install common system essentials
  apt:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
      - git
      - vim
      - htop

- name: Turn off wifi power saving
  lineinfile:
    path: /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
    regexp: '^wifi.powersave ='
    line: wifi.powersave = 2
  become: true

- name: Disable firewall to allow ROS communication
  command: ufw disable
  become: true
