- name: Reconfiguring hostname
  command: hostnamectl set-hostname robotont-{{ id }}
  become: true

- name: Configuring hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.1.1'
    line: 127.0.1.1   robotont-{{ id }}
  become: true

- name: Deploy AP wifi profile
  template:
    src: robotont-ap.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/robotont-ap.nmconnection
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Deploy client wifi profile
  template:
    src: robotont-client.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/robotont-client.nmconnection
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Reload NetworkManager connections
  command: nmcli connection reload
  become: true

- name: Prefer client connection if available
  command: "nmcli connection up {{ wifi_client_ssid }}"
  become: true

- name: Reboot the machine
  reboot:
  become: true
  ignore_errors: true
