---
- name: Remove excessive ubuntu software
  apt:
    name: "{{ packages }}"
    state: absent
    purge: true
  become: true
  vars:
    packages:
      - libreoffice*

#- name: Cleaning up launcher icons
#  command: gsettings set org.gnome.shell favorite-apps "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop']"
#  become: false

- name: Give user access to the serial ports and joysticks
  user:
    name: "{{ robotont_user }}"
    groups: dialout,input
    append: yes
  become: true

- name: Downloading udev rules for realsense camera
  command: wget -O /etc/udev/rules.d/99-realsense-libusb.rules https://raw.githubusercontent.com/IntelRealSense/librealsense/master/config/99-realsense-libusb.rules
  become: true

# Make robotont mcu always appear as /dev/robotont
- name: Downloading udev rules for robotont driver
  copy:
    src: resources/99-robotont.rules
    dest: /etc/udev/rules.d/99-robotont.rules
    owner: root
    group: root
    mode: '0644'
  become: true
 
- name: Reloading udev rules
  shell: |
    udevadm control --reload-rules
    udevadm trigger
  become: true
  
- name: Install additional APT packages for the robot
  apt:
    name: "{{ packages }}"
  become: true
  vars:
    packages: "{{ item }}"
  with_items: "{{ apt_packages }}"
  when: (apt_packages is defined) and (apt_packages is not none)
  become: true


#Service setup
- name: Set up a systemd service for Robotont
  template:
    src: robotont.service.j2
    dest: /lib/systemd/system/robotont.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable and start the service
  service:
    name: robotont.service
    state: started
    enabled: yes
  become: true
    
- name: Reconfiguring hostname 
  command: hostnamectl set-hostname robotont-{{ id }}
  become: true
  
- name: Configuring hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.1.1'
    line: 127.0.1.1   robotont-{{ id }}
  become: true
    
- name: Configuring /etc/netplan/01-network-manager-all.yaml
  template:
    src: robot_netplan.j2
    dest: /etc/netplan/01-network-manager-all.yaml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Apply netplan
  command: netplan apply
  become: true

  #- name: Apply connection
  #  command: nmcli connection up netplan-wlp58s0-robotont-{{ id }}
  #  become: true

- name: Unconditionally reboot the machine with all defaults
  reboot:
  become: yes
  ignore_errors: true
