---
- name: Remove excessive ubuntu software
  apt:
    name: "{{ packages }}"
    state: absent
    purge: true
  become: true
  vars:
    packages:
      - libreoffice*

- name: Disable services that are not needed for the robot
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - cups
    - cups-browsed
    - ModemManager
    - whoopsie
    - apport
    - speech-dispatcher
    - accounts-daemon
  become: true

#- name: Cleaning up launcher icons
#  command: gsettings set org.gnome.shell favorite-apps "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop']"
#  become: false

- name: Give user access to the serial ports, joysticks, and video devices
  user:
    name: "{{ robotont_user }}"
    groups: dialout,input,video
    append: yes
  become: true

# Make robotont mcu always appear as /dev/robotont
- name: Downloading udev rules for robotont driver
  copy:
    src: resources/99-robotont.rules
    dest: /etc/udev/rules.d/99-robotont.rules
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: udev
 
- name: Reloading udev rules
  shell: |
    udevadm control --reload-rules
    udevadm trigger
  become: true
  tags: udev
  
- name: Install additional APT packages for the robot
  apt:
    name: "{{ packages }}"
  vars:
    packages: "{{ item }}"
  with_items: "{{ apt_packages }}"
  when: (apt_packages is defined) and (apt_packages is not none)
  become: true


- name: Set up rpi ai camera support
  import_tasks: imx500_camera.yaml
  tags: camera

#Service setup
- name: Set up a systemd service for Robotont
  template:
    src: robotont.service.j2
    dest: /lib/systemd/system/robotont.service
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: service

- name: Enable and start the service
  service:
    name: robotont.service
    state: started
    enabled: yes
  become: true
  tags: service
    
- name: Reconfiguring hostname 
  command: hostnamectl set-hostname robotont-{{ id }}
  become: true
  tags: id
  
- name: Configuring hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.1.1'
    line: 127.0.1.1   robotont-{{ id }}
  become: true
  tags: id
    
- name: Deploy AP wifi profile
  template:
    src: robotont-ap.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/robotont-ap.nmconnection
    owner: root
    group: root
    mode: '0600'
  become: true
  tags: net

- name: Deploy client wifi profile
  template:
    src: robotont-client.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/robotont-client.nmconnection
    owner: root
    group: root
    mode: '0600'
  become: true
  tags: net

- name: Reload NetworkManager connections
  command: nmcli connection reload
  become: true
  tags: net

- name: Prefer client connection if available
  command: "nmcli connection up {{ wifi_client_ssid }}"
  become: true
  tags: net

- name: Unconditionally reboot the machine with all defaults
  reboot:
  become: yes
  ignore_errors: true
