# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eno1:
      dhcp4: true
      optional: true
  wifis:
    wlan0:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.200.{{ id }}/24]
      nameservers:
        addresses: [8.8.8.8]
      access-points:
        "robotont-{{ id }}":
          mode: ap
          password: "{{ wifi_password }}"
