---
- hosts: robots
  remote_user: "{{ ansible_user }}"

  tasks:
  - name: Update hostname to robotont-{{ id }}
    hostname:
      name: "robotont-{{ id }}"
    become: true

  - name: Update /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: Unconditionally reboot the machine with all defaults
    reboot:
    become: yes
