---
- hosts: clearbots
  remote_user: kasutaja
  tasks:

  - name: Add ROS keys
    become: true
    apt_key:
      keyserver: ha.pool.sks-keyservers.net
      id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

  - name: Setup compute to accept software from packages.ros.org
    become: true
    apt_repository:
      repo: deb http://packages.ros.org/ros/ubuntu bionic main
      state: present

  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes

  - name: Full ROS installation
    become: true
    apt:
      name: ros-melodic-desktop-full

  - name: Check if rosdep has already been initalised
    stat:
      path: /etc/ros/rosdep/sources.list.d/20-default.list
    register: already_init

  - name: Run rosdep init
    command: rosdep init -y --reinstall
    become: true
    when: already_init.stat.exists == False

  - name: Run rosdep update
    command: rosdep update

  - name: Put the ROS setup script in bashrc
    lineinfile:
      path: /home/kasutaja/.bashrc
      line: 'source /opt/ros/melodic/setup.bash'

  - name: Install dependencies for building ROS packages
    apt:
      name: "{{ packages }}"
    become: true
    vars:
      packages:
        - python-rosinstall
        - python-rosinstall-generator
        - python-wstool
        - build-essential
        - python-catkin-tools

  # The following tasks are experemental

  # Solution to an issue as detailed here: https://answers.ros.org/question/201225/roscore-fails-to-start/
  #  - name: Add the correct ros_hostname
  #    lineinfile:
  #      path: /home/kasutaja/.bashrc
  #      line: 'export ROS_HOSTNAME=localhost'
