---
# Main tasks for the ROS role
- name: Set locale for ROS installation
  include: ros-locale.yaml
  tags: ros-locale

- name: Install ROS
  include: ros-install.yaml
  tags: ros-install

- name: ROS Packages Install
  include: ros-packages-install.yaml
  tags: ros-packages-install

- name: ROS Workspace Setup
  include: ros-workspace-setup.yaml
  tags: ros-workspace-setup