---
- name: Clean up build install and log files in {{ ros_ws }}
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "{{ ros_ws }}/build"
      - "{{ ros_ws }}/install"
      - "{{ ros_ws }}/logs"

- name: Create ROS workspace folders 
  file:
    path: "{{ ros_ws }}/src"
    state: directory
    owner: "{{ robotont_user }}"
    group: "{{ robotont_group }}"
    mode: '0775'
  become: true
  become_user: "{{ robotont_user }}"

- name: Copy .rosinstall file with owner and permissions for laptop
  copy:
    src: "{{ ros_ws_install_file }}"
    dest: "{{ ros_ws }}/src/.rosinstall"
    owner: "{{ robotont_user }}"
    group: "{{ robotont_group }}"
    mode: '0644'
  become: true
  become_user: "{{ robotont_user }}"

- name: Update ROS workspace from .rosinstall
  shell: bash -ic 'vcs import < .rosinstall'
  args:
    chdir: "{{ ros_ws }}/src"
  become: true
  become_user: "{{ robotont_user }}"

- name: Run rosdep update under root user
  command: rosdep update
  become: true

- name: Install ROS workspace dependencies
  shell: |
    MISSING_KEYS=$(rosdep check --from-paths src --ignore-src --rosdistro {{ ros_distribution }} 2>&1 \
      | grep "rosdep key :" | awk -F ':' '{gsub(/^[ \t]+/, "", $2); print $2}')

    if [ -n "$MISSING_KEYS" ]; then
      SKIP_LIST=$(echo "$MISSING_KEYS" | paste -sd, -)
      rosdep install --from-paths src --ignore-src --rosdistro {{ ros_distribution }} -y --skip-keys="$SKIP_LIST"
      echo "$SKIP_LIST"
    else
      rosdep install --from-paths src --ignore-src --rosdistro {{ ros_distribution }} -y
    fi
  args:
    chdir: "{{ ros_ws }}"
    executable: /bin/bash
  register: rosdep_missing_keys
  become: true
  changed_when: false
  failed_when: false

- name: Print missing rosdep keys
  shell: |
    echo "Missing rosdep keys: {{ rosdep_missing_keys.stdout }}"
  when: rosdep_missing_keys.stdout != ""
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ robotont_user }}"

- name: Build ROS workspace 
  shell: bash -ic 'colcon build'
  args: 
    chdir: "{{ ros_ws }}" 
  become: true
  become_user: "{{ robotont_user }}"

- name: Update .bashrc with ROS workspace setup script
  lineinfile:
    path: /home/{{ robotont_user }}/.bashrc
    line: source {{ ros_ws }}/install/setup.bash
  become: true
  become_user: "{{ robotont_user }}"
